#! /bin/sh
case "$1" in
    configure)
 	iconv -c -f EUC-JP -t UTF-8 /usr/share/edict/kanjidic -o /usr/share/gjiten/dics/kanjidic
	iconv -c -f EUC-JP -t UTF-8 /usr/share/edict/edict -o /usr/share/gjiten/dics/edict
	iconv -c -f EUC-JP -t UTF-8 /usr/share/edict/compdic -o /usr/share/gjiten/dics/compdic
	if [ -f /usr/share/edict/enamdict ]; then 
	    iconv -c -f EUC-JP -t UTF-8 /usr/share/edict/enamdict -o /usr/share/gjiten/dics/enamdict
	fi
        GCONF_CONFIG_SOURCE=`gconftool-2 --get-default-source` gconftool-2 --makefile-install-rule /etc/gconf/schemas/gjiten.schemas > /dev/null
        GCONF_CONFIG_SOURCE=`gconftool-2 --get-default-source` gconftool-2 --makefile-install-rule /etc/gconf/schemas/gjiten-dicfiles.schemas > /dev/null
	scrollkeeper-update -q
    ;;
    
    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

esac

#DEBHELPER#

exit 0
